name: project_zoe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
  supabase_flutter: ^2.5.11
  go_router: ^14.2.3
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.4.0
  json_serializer: ^0.2.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: HKIcons
      fonts:
        - asset: assets/fonts/icons/HKIcons.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png"
  adaptive_icon_background: "#ffeda313"
  remove_alpha_ios: true